{-
   IEX Haskell SDK

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.0
   IEX Haskell SDK API version: 1.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : IEXHaskellSDK.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module IEXHaskellSDK.Logging
  ( module IEXHaskellSDK.LoggingKatip
  ) where

import IEXHaskellSDK.LoggingKatip

#else

module IEXHaskellSDK.Logging
  ( module IEXHaskellSDK.LoggingMonadLogger
  ) where

import IEXHaskellSDK.LoggingMonadLogger

#endif
